---
title: "Data"
author: "Zhikuan Quan"
date: "01/26/2020"
output: html_document
---

# Input the Data

The primary student-level data file contains information on 11,601 students who participated in the experimental phase for at least one year.

```{r}
library(haven)
library(tidyverse)
STAR_Student <- read_sav("STAR_Students.sav")

# Select the data of 1st graders
STAR <- STAR_Student %>%
  select(stdntid,gender,race,contains("g1"))
```


```{r}
# omitting the missing value
STARF <- STAR %>%
  filter(complete.cases(STAR))
```

```{r}
# Data only with Math Scores, class type, teacher ID
STAR1 <- STAR %>%
  select(g1classtype,g1tmathss,g1tchid)
# omitting the missing value
STARF1 <- STAR1 %>%
  filter(complete.cases(STAR1))
```

```{r}
# One teacher teaches in one type of class
START <- STAR_Student %>%
  select(g1classtype,g1tchid) %>%
  transmute(class = as.factor(g1classtype), id = as.factor(g1tchid)) %>%
  filter(complete.cases(.))

# One teacher teaches in one school
STARTT <- STAR_Student %>%
  select(g1tchid,g1schid) %>%
  transmute(school = as.factor(g1schid), id = as.factor(g1tchid)) %>%
  filter(complete.cases(.))

```

```{r}
# Get data of teacherid(tid), classtype(class), schoolid(sid), mathscore(math)
# Teacher as a unit
DATA <- STAR_Student %>%
  select(g1classtype,g1tmathss,g1tchid,g1schid) %>%
  filter(complete.cases(.)) %>%
  group_by(g1tchid,g1classtype,g1schid) %>%
  summarize(math = mean(g1tmathss, na.rm = TRUE)) %>%
  rename(tid = g1tchid, class = g1classtype, sid = g1schid)
```

