---
title: "Two-way ANOVA"
author: "Zhikuan Quan"
date: "01/27/2020"
output: html_document
---

```{r}
## Input Data
library(haven)
library(tidyverse)
library(car)
library(nortest)
library(MASS)
library(FSA)
library(rcompanion)
STAR_Student <- read_sav("STAR_Students.sav")

DATA <- STAR_Student %>%
  select(g1classtype,g1tmathss,g1tchid,g1schid) %>%
  filter(complete.cases(.)) %>%
  group_by(g1tchid,g1classtype,g1schid) %>%
  summarize(math = mean(g1tmathss, na.rm = TRUE)) %>%
  rename(tid = g1tchid, class = g1classtype, sid = g1schid)
DATA$sid<-as.factor(DATA$sid)
DATA$class<-as.factor(DATA$class)
DATA$tid<-as.factor(DATA$tid)



```



```{r}
## Two-way ANOVA With interaction
res.aovt <- aov(math ~ sid + class + class*sid, data = DATA)
summary(res.aovt) 
# interaction term is not significant (Since class size and school id are independent)


## Two-way ANOVA without interaction
res.aov <- aov(math ~ sid + class, data = DATA)
summary(res.aov) 
# family-wise -> significance
# the class size is significantly associated with math scores
# the school id is significantly associated with math scores
```


```{r}
### Model Diagnostics ###

## 1. Normality
# plot test: heavy-tailed
plot(res.aov, 2)
ad.test(residuals(res.aov))

## 2. Homogeneity of variances
# plot test: hard to distinguish pattern -> use other method
plot(res.aov, 1)
# Anderson-Darling normality test
ad.test(residuals(res.aov))$p.value
# p<0.05, reject H0, so residuals are not normally distributed.

# Use the Levene’s test to check the homogeneity of variances. 
leveneTest(math ~ sid*class, data=DATA)
# p<0.05, this means that it is evident to suggest that the variance across groups is statistically significantly different.

## Conclusion: non-normality, non-constant variance.
```

```{r}
# trace interaction
attach(DATA)
interaction.plot(class,sid,math)

friedman.test(math,class,sid, data = DATA)
kruskal.test(math,class,sid, data = DATA)
detach(DATA)
```

```{r}
full_model=lm(math ~ class + sid + class*sid,data=DATA)
reduced_model=lm(math ~ class + sid ,data=DATA)
anova(reduced_model,full_model)

```

```{r}

DATA1<-data.frame(math = rank(DATA$math), class = rank(DATA$class),id =rank(DATA$sid))
summary(aov(math~class+id,data=DATA1))

#friedman.test(math ~ class | sid, data = DATA1)

#table(DATA$class)
#kruskal.test(math , class, data = DATA)


scheirerRayHare(math ~ class + sid, data = DATA)

dunnTest(math ~ class, data=DATA, method="bh") 
```
